@startuml
!include <c4/C4_Context.puml>
!include <C4/C4>  
!include <C4/C4_Container>     

Person(customer, "Nutzer")
  System(webApp, "Gewohnheitstier\n - Habit Tracker",  "Erlaubt Nutzern ihre Habits zu erstellen, anzeigen zu lassen, zu bearbeiten und zu löschen. ")



  ContainerDb_Ext(db,    "Supabase",  "Datenbank Provider", "Datenhaltung: Enthält User, Habits, Streaks und User-Beziehungen")


Rel(customer, webApp, "Erstellt und trackt Habits \n Intergiert mit anderen Usern \n durch ")

Rel_R(webApp, db,     "UserManagement, Authentfication, Datenhaltung")

@enduml