@startuml
!include <c4/C4_Context.puml>
!include <C4/C4>  
!include <C4/C4_Container> 

Person(user, "Nutzer", "Möchte seine Habits tracken")
System_Boundary(gewohnheitstier, "Gewohnheitstier") {
  Container(webApp, "Web-Frontend", "React", "UI für Nutzerinteraktion")
  Container(api,    "Backend API", "Node.js/Express.js", "Verarbeitet Anfragen und führt Logik aus")
  
  Container(mobileApp, "Mobile App(Optional)", "JavaScript/Expo", "Mobile UI für Nutzerinteraktion")
  ContainerDb(db,    "Database(Supabase)",  "PostgreSQL", "Datenspeicherung")
}



Rel(user, webApp, "nutzt")
Rel(user, mobileApp, "nutzt")
Rel(webApp,    api,    "REST-Calls")
Rel(mobileApp, api, "REST-Calls")
Rel_R(api,       db,     "SQL-CRUD")

@enduml
