= Demo-Dokumentation
Patrick Eger <patrick.eger@htw-dresden.de>
include::attributes.inc.adoc[]
:imagesdir: images 
:diagramsdir: diagrams 
:plantumlsdir: plantuml 
Praktikumsbeispiel für die Verwendung von Diagrammen mit PlantUML in Asciidoctor.


== PlantUML-Diagramme

Diagramme mit der PlantUML-Notation können im Asciidoctor-Dokument direkt als Block *eingebettet* oder als externe Datei *inkludiert* werden.
.Klassendiagramm mit PlantUML 
[plantuml, "{diagramsdir}/syntax-example1", svg]  
....
class Graphic 
interface Shape <<Interface>> {
  draw()
}
class Circle
class Triangle
class Square

Graphic -> Shape
Shape <|.. Circle
Shape <|.. Triangle
Shape <|.. Square
....

=== Funktionstest

Ein Testdiagramm, ob die Vorschau in VS Code bzw. die Generierung mit Asciidoctor funktioniert.

.Testdiagramm
[plantuml, "{diagramsdir}/hello_world", svg]
....
actor Human
(\nWorld\n) #dff
note right of Human : Hello
....

.Graphiz Dot Test
[plantuml, "{diagramsdir}/testdot", svg]
....
@startuml
testdot
@enduml
....

Hinweise zur Einrichtung siehe zugehörige Aufgabenstellung.

=== Eingebettet

Ein Beispiel für ein direkt im Dokument eingebettetes PlantUML-Diagramm.

// diagram placeholder

=== Inkludiert

Ein Beispiel für ein im Dokument inkludiertes PlantUML-Diagramm als externe Datei.

// diagram placeholder

=== C4 Modell
[plantuml, "{diagramsdir}/c4", svg]
....
include::{plantumlsdir}/c4.puml[]
....

=== Klassendiagramm
[plantuml, "{diagramsdir}/syntax-example3", svg]  
....
@startuml
' left to right direction
hide circle
hide empty members

' Abstand (horizontal)
skinparam nodesep 100

' Minimale Breite der Klassen
<style>
class {
  MinimumWidth 100
}
</style>

title "Domänenklassen"

' Klassen vordefinieren
class "Cocktail" as c1 {
  ' Attribute
  name
}
class "Standard" as c2
class "Individual" as c3
class "Zutat" as c4

' Assoziation
Kunde -- Adresse

' Spezialisierung
c1 <|-- c2
c1 <|-- c3

' Multiplizitäten
c1 "0..*" -r-- "1..*" c4

footer


<font color=gray>Angaben nur beispielhaft!</font>
endfooter

@enduml
....
=== Klassendiagramm
[plantuml, "{diagramsdir}/syntax-example4", svg]  
....
@startuml example-class-diagram
class MyService {
  -repository : MyRepository
  +MyService(MyRepository)
  +getProcessedStudents() : List
  +getProcessedMarks() : List
}

interface MyRepository <<interface>> {
  +getStudents() : List
  +getMarks() : List
}

class DictionaryRepository {
  -data : TestData
  +getStudents() : List
  +getMarks() : List
}

class TestData {
  #students : Dictionary
  #marks : Dictionary
  +generateKey(Student, SubjectMark) : String
}

class MsSqlRepository {
  -connection : OdbcConnection
  +getStudents() : List
  +getMarks() : List
}

MyService --> "1" MyRepository
MyRepository <|.. DictionaryRepository
MyRepository <|.. MsSqlRepository
TestData "1" <- DictionaryRepository

note left of MyRepository: Interface for local test data\nand different databases
@enduml
....

=== Anwendungsfalldiagramm
[plantuml, "{diagramsdir}/syntax-example5", svg]
....
@startuml example-usecase-diagram
left to right direction

' skin parameters for usecase with special stereotype
skinparam usecase<<unspezifiziert>> {
  BackgroundColor #eee
  BorderColor #gray
  StereotypeFontColor #gray
  StereotypeFontSize 10
}

actor Nutzer
actor Service

rectangle "eRoller App" {
  usecase "UC01\nRoller finden" as uc01
  usecase "UC02\nRoller freischalten" as uc02
  usecase "UC03\nRoller abstellen" as uc03
  usecase "UC04\nRoller melden" as uc04

  ' single line:
  'usecase "UC05\nAnmeldedaten erfassen" as uc05
  ' multiple lines:
  usecase uc05 as "UC05
  Anmeldedaten erfassen"

  usecase "UC06\nRoller verwalten" <<unspezifiziert>> as uc06
}

Nutzer -- uc01
Nutzer -- uc02
Nutzer -- uc03
Nutzer -- uc04
uc02 .down.> uc05 : include
Service -- uc06
@enduml
....

=== Aktivitätsdiagramm
[plantuml, "{diagramsdir}/syntax-example6", svg]
....
@startuml example-activity-diagram
start

:Initialization;
note right: The first <del>Avenger</del> Activity

if (Some Test) then (yes)
  :Some Activity;
  #LightBlue:Object; /'idea: activity as object flow'/
  :Another Activity;
else (no)
  :Something else;
  note right #LightBlue: Object /'idea: note as object'/
endif

:Final Activity;

stop
@enduml
....