include::../docs/_includes/default-attributes.inc.adoc[]
// ---
:doctype: book
//:toc:
//:toclevels: 2
//:toc-title: Inhaltsverzeichnis
//:sectnums:
//:icons: font
//:source-highlighter: highlightjs
:source-highlighter: rouge
:rouge-style: github
:xrefstyle: full
:experimental:
:chapter-signifier:
:figure-caption: Abbildung
:table-caption: Tabelle
:listing-caption: Listing
:!example-caption:
:experimental:
// Folders
:imagesdir-reset: {imagesdir}
:docs-test2: {docs}/test2
:docs-requirements: {docs}/requirements
:docs-project-management: {docs}/project_management
:docs-architecture: {docs}/architecture
:docs-test: {docs}/test
:docs-development: {docs}/development

// --- Betriebsdokumentation ---
== Betriebsdokumentation
Ziel dieser Betriebsdokumentation ist es, Administratoren beim Einrichten, Konfigurieren, Betreiben und Warten unserer Anwendung zu unterstützen.
Dieses Dokument beschreibt ausschließlich systemspezifische Besonderheiten. Allgemeine Software-Dokumentationen (z.B. Docker, Supabase/PostgreSQL, React, Prisma) werden bei Bedarf verlinkt.

=== Übersicht der verwendeten Technologien
Die Anwendung arbeitet über ein Mehrcontainer-System. Das heißt die Anwendung wurde nach Schichten getrennt und in etwaige Container aufgeteilt, in welchen Prozesse losgelöst voneinander laufen. Die Trennung dient dabei der erleichterten Wartbarkeit und erfolgt nach dem Prinzip der "Seperation of Concerns". 

Die Containersisierung erfolgt mittels link:https://docs.docker.com/compose/[Docker Compose] und erzeugt die folgenden Images bzw. Container:

* *gewohnheitstier-frontend*:
** Web-UI als React-SPA (Create React App) 
** Schnittstellen zum Backend
** veröffentlicht auf Port 3000 des Hostgerätes

* *gewohnheitstier-backend*:
** Logikschicht
** Schnittstellen zum Frontend
** Schnittstellen zur Datenbank sowie Authentifizierung (link:https://supabase.com/[Supabase])
** veröffentlicht auf Port 3001 des Hostgerätes


=== Systemvorraussetzungen
==== Hardware-Mindestanforderungen
Eine Abschätzung der benötigten Ressourcen kann zum aktuellen Zeitpunkt nur durch lokales Beobachten der Container erfolgen. Eine gemittelte Messung der Aktivitäten unter Last (Mehrnutzer-Betrieb) ist noch offen und könnte hier zu genaueren Angaben beitragen. Die folgende Abschätzung benötigter Hardwareressourcen ist daher keine untere Schranke. Die Anwendung kann unter Umständen auf geringeren Spezifikationen ausgeführt werden, jedoch können wir nicht dafür garantieren. Daher empfehlen wir folgende Spezifikationen:

* 64-bit Architektur
* Multicore-CPU oder 2vCPU (>1GHz)
* KVM Virtualisierung unterstützt
* min. 4GB RAM
* 50 GB freier Speicherplatz
* Ubuntu LTS 24.xx.x Desktop oder Server
* stabile, schnelle Internetverbindung

==== Softwarevorraussetzungen
Auf dem System muss Docker bzw. Docker Compose installiert und lauffähig sein. Dafür kann die offizielle Dokumentation herangezogen werden (link:https://docs.docker.com/[Docker]).
Der Admin oder Betreiber benötigt Zugriff auf das Terminal des Hostgeräts und ggf. Sudo-Rechte um Portfreigaben tätigen zu dürfen.

Die Anwendung ist durchaus auf anderen Betriebssystem ausführbar, wie in etwa andere Linux-Distributionen, MacOS oder Windows. Sollten Sie Schwierigkeiten dabei haben die Anwendung auf einem anderen Betriebssystem auszuführen, so kontaktieren Sie bitte die genannten Personen am Ende des Dokuments.  

=== In-Betriebnahme
==== Umgebung einrichten



