include::../docs/_includes/default-attributes.inc.adoc[]
// ---
:doctype: book
//:toc:
//:toclevels: 2
//:toc-title: Inhaltsverzeichnis
//:sectnums:
//:icons: font
//:source-highlighter: highlightjs
:source-highlighter: rouge
:rouge-style: github
:xrefstyle: full
:experimental:
:chapter-signifier:
:figure-caption: Abbildung
:table-caption: Tabelle
:listing-caption: Listing
:!example-caption:
:experimental:
// Folders
:imagesdir-reset: {imagesdir}
:docs-test2: {docs}/test2
:docs-requirements: {docs}/requirements
:docs-project-management: {docs}/project_management
:docs-architecture: {docs}/architecture
:docs-test: {docs}/test
:docs-development: {docs}/development

// --- Betriebsdokumentation ---
== Betriebsdokumentation
Ziel dieser Betriebsdokumentation ist es, Administratoren beim Einrichten, Konfigurieren, Betreiben und Warten unserer Anwendung zu unterstützen.
Dieses Dokument beschreibt ausschließlich systemspezifische Besonderheiten. Allgemeine Software-Dokumentationen (z. B. Docker, Supabase/PostgreSQL, React, Prisma) werden bei Bedarf verlinkt.

=== Übersicht der verwendeten Technologien
Eine detailreichere Auflistung der verwendeten Technologien ist der Entwicklerdokumentation zu entnehmen. Die folgende Auflistung dient lediglich dem Zweck einen Kontext zum Gesamtsystem herstellen zu können.

* Frontend: React (Create React App) mit Tailwind CSS
* Backend: Node.js mit Express
* ORM: Prisma
* Datenbank: PostgreSQL (Supabase)

* Containerisierung: Docker Compose
** Umgebungen: Development (DEV) und Production (PROD)

Die Anwendung ist als Mehrcontainer-System realisiert worden. Das heißt es existiert jeweils ein Container für Front- und Backend. Die Trennung dient der erleichterten Wartbarkeit sowie Testbarkeit (siehe Testdokumentation) und erfolgt nach dem Prinzip der "Seperation of Concerns".  

=== Systemvorraussetzungen
==== Hardware-Mindestanforderungen
Eine Abschätzung der benötigten Ressourcen kann zum aktuellen Zeitpunkt nur durch lokales Beobachten der Container erfolgen. Eine gemittelte Messung der Aktivitäten unter Last (Mehrnutzer-Betrieb) ist noch offen und könnte hier zu genaueren Angaben beitragen.

