services:
  backend:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env.local
    environment:
      NODE_ENV: development
      NPM_SCRIPT: dev
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    env_file:
      - frontend/.env
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
