= Meeting 09.12.2025 (weekly)
Anwesend: Monika, Felix, Tristan, Martin, Paul, Nicola, Patrick

== Besprechen
-   Dokumentation Testfälle für Akzeptanzkriterien der abgeschlossenen UserStories => doc/testcases (Issue von Tristian)
-   Präsentation Farbkonzept (Felix) => Entscheidung => Anpassung und Ausarbeitung (Felix)



== Besprechen - Änderungen / Ergänzungen Doku:
-   Architecture-Notebook:
    * Annahmen/Abhängigkeiten: Prisma + Docker (stattdessen mpm?)
    * Arch.-relevante Anforderungen: Responsives Design?
    
-   Project-Plan:
    * Deployment: Beschreibung, wie Client/Server gestartet wird (Paul, Tristan)

== To Do's
-   Überlegung / Beschreibung der Anwendung von Methoden, die gut bzw. nicht gut funktioniert haben (Team-Tops/Team-Flops) (alle => Miro)
-   Termin für Präsentation (20. oder 27.01.26) => Entscheidung für 20.01.26 (Martin)
-   Wissensaufbau automatische Doku (Software, UML, Klassen/Methoden) => (Tristan, Paul)
-   Domänenmodell anpassen (Nicola)
-   Überarbeitung Layout (Flexboxen)
-   Beginn Anwenderdoku (Felix, Martin)
-   Frontend-Tests implementieren (Patrick)

-   Datenstrukturen (DB-Tabellen) ergänzen (Doku Glossar: Martin)
-   Infos aus Doku Container in Doku (Doku Deployment: Martin)

== Done
-   "Review-Fahrplan"
    => Laptop Patrick: Login, Registrierung, Habit anlegen, Habit ausfüllen, Habit löschen, Kalenderfunktion
-   abzugebende Dokumente für Beleg
-   Konsultation
-   Timeful ausfüllen bis Jahresende (Tristan)
-   Domänen-Modell ändern / anpassen für neue Funktionen (Futter usw.) => nur aktuellen Stand darstellen (zukünftige Planungen raus) (Nicola)
-   VL nacharbeiten und wichtige Infos zusammenfassen => ?? (Monika => Miro)
-   Farben mittels CSS benennen, um Farbkonzept später einführen bzw. ändern zu können (Patrick, Felix)
-   Planung/Vorbereitung Unit-Tests (Martin, Paul)
-   Vorbereitung Vortrag Fachaustausch Tests (Martin), z.B. Protokoll für explorative Tests

=> Weekly:  09.12. vor der VL um 13.00 Uhr in Z 136c (Bib-Gruppenarbeitsraum)
=> Retro:   evtl. 20.12. 18.00 Uhr online?
